name: Publish CLI

on:
  release:
    types: [published]

env:
  PROJECT_NAME: QuizConsole

jobs:
  build:
    strategy:
      matrix:
        os: [{ os: windows-latest, runtime: win-x64 }, { os: windows-latest, runtime: win-x86 }, { os: ubuntu-latest, runtime: linux-x64 }]

    runs-on: ${{ matrix.os.os }}
    name: Build on ${{ matrix.os.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish ${{ matrix.os.runtime }}
        run: dotnet publish ${{ env.PROJECT_NAME }} -c Release -f net7.0 -r ${{ matrix.os.runtime }} -o build/${{ env.PROJECT_NAME }}-${{ matrix.os.runtime }} -p:PublishSingleFile=true -p:EnableCompressionInSingleFile=true -p:PublishTrimmed=true -p:TrimMode=partial --self-contained

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: build
          path: build

  publish:
    needs: build

    strategy:
      matrix:
        os: [{ os: windows-latest, runtime: win-x64 }, { os: windows-latest, runtime: win-x86 }, { os: ubuntu-latest, runtime: linux-x64 }]

    runs-on: ${{ matrix.os.os }}
    name: Upload ${{ matrix.os.os }}

    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: build

      - name: Zip to ${{ env.PROJECT_NAME }}-${{ matrix.os.runtime }}.${{ github.ref_name }}.zip
        uses: thedoctor0/zip-release@main
        with:
          path: ${{ env.PROJECT_NAME }}-${{ matrix.os.runtime }}
          filename: ${{ env.PROJECT_NAME }}-${{ matrix.os.runtime }}.${{ github.ref_name }}.zip

      - name: SHA256 checksum
        uses: Huy-Ngo/gha-sha@v1.1.0
        with:
          glob: ${{ env.PROJECT_NAME }}-${{ matrix.os.runtime }}.${{ github.ref_name }}.zip

      - name: Upload ${{ env.PROJECT_NAME }}-${{ matrix.os.runtime }}.${{ github.ref_name }}.zip to this release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/releases/${{ github.event.release.id }}/assets?name=${{ env.PROJECT_NAME }}-${{ matrix.os.runtime }}.${{ github.ref_name }}.zip \
            -f '@${{ env.PROJECT_NAME }}-${{ matrix.os.runtime }}.${{ github.ref_name }}.zip'
